### ISSUE TITLE
Mailing list issues

### ISSUE THREAD

**Issue by Aaronontheweb** [KilleenCode/dotnetfringe.github.io#33]
* [ ] Need to fix CSS so the box and form are styled correctly
* [ ] Need to fix JS / CSS so text can actually be input onto the form
* [ ] Need to do a test-run to see that the form can actually be submitted correctly
* [ ] Need to add signup link to the mailing list from header

**Comment by Aaronontheweb** [comment]
CSS issues, visualized:

![image](https://cloud.githubusercontent.com/assets/326939/23079364/876689c2-f501-11e6-878a-fb8c66dad6f2.png)

needs to be yellow line at the bottom, bounding the signup box and the text-form needs to match the size of the button itself

**Comment by Aaronontheweb** [comment]
All of the mailing list changes are in the `mailing-list` branch, which is now pushed cc @SeanKilleen @RyKilleen

**Comment by SeanKilleen** [comment]
@Aaronontheweb :+1:
